### ISSUE TITLE
[BUG] No se deberían agregar salto de líneas a archivos vacíos

### ISSUE THREAD

**Issue by darkmx** [omegaup/gitserver#13]
Hola amigos de omegaUp.

Si un caso de prueba no termina en salto de línea, la plataforma lo agrega automáticamente. Eso me causó problemas en el pasado con un problema de manipulación de archivos (https://omegaup.com/preguntas/1035/salto-de-línea-al-final-de-casos-de-prueba) pero jamás me había causado problemas con un problema "ordinario", hasta ahora.

Resulta que en la cola de nominaciones, un usuario con 90% reportó mi problema https://omegaup.com/problem/Anyos-con-dos-y-cuatro-digitos por casos incorrectos. El problema se trata de procesar todas las líneas que vengan en la entrada (y se supone que todas las líneas que vienen en la entrada tienen un formato válido). El caso de entrada que el usuario tiene "mal" es el primero, el cual originalmente era un archivo vacío. Resulta que la plataforma le está agregando un salto de línea a ese archivo vacío y también resulta que el código del usuario es "¿pude leer una línea? entonces se supone que conozco su formato: procésala". Ese proceso involucra extraer enteros de la línea, los cuales no aparecerán en este caso.

Nunca he estado del todo convencido de que meterle mano a los casos de prueba sea una buena idea y la interacción que ocurrió aquí fue bastante fea. Claramente puedo quitar el archivo con el caso vacío o también puedo decir que pueden venir líneas vacías que deben ser ignoradas, pero honestamente creo que no debió haber sido necesario. Como autor siento feo el tiempo que el usuario perdió intentando el problema, pero por otro lado, también siento que no fue mi culpa.

De leer https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline (lo que menciona el estándar de C sobre los archivos fuente) y https://unix.stackexchange.com/questions/446237/what-conditions-must-be-met-for-a-file-to-be-a-text-file-as-defined-by-posix, pareciera ser que un archivo vacío es un "archivo de texto" válido, por lo que no debería ser necesario agregarle un salto de línea.

**Comment by darkmx** [comment]
Hola, una preg. Ahorita intenté volver a subir los casos del problema mencionado, pero al archivo en blanco se le sigue agregando un salto de línea. Sospecho que el bugfix aún no está live, pero quisiera confirmar.

**Comment by lhchavez** [comment]
correcto, no se ha hecho el deploy. se hará este domingo
